public enum WorkType {
    TRAVAUX_ROUTIER,
    TRAVAUX_GAZ_ELEC,
    RENOVATION,
    ENTRETIEN_PAYS,
    TRANSPORT_COMMUN,
    SIGNALISATION_ECLAIR,
    SOUTERRAIN,
    RESIDENTIEL,
    URBAIN,
    TELECOM
}
